language: python
python:
    - 3.6

install:
    - pip install -r requirements_dev.txt
    - pip install -r requirements.txt

script:
    - flake8 candig_authz_service/
    - pytest --cov=candig_authz_service tests
